module.exports = [
    {
        "createdAt": "1546855273349",
        "updatedAt": "1547015769476",
        "id": 1,
        "areaname": "陕西区域",
        "status": "0",
        "projects": [
            {
                "createdAt": null,
                "updatedAt": "1547090354807",
                "id": 6,
                "name": "榆林-市局项目",
                "area": "1",
                "dutyPerson": "3",
                "createPerson": "3",
                "prods": "1,3,4,5",
                "summary": "接入：3801路视频，578路卡口，20路人脸抓拍机，视频结构化20路，结构化能力160路。日均数据量约为500万+。",
                "number": "4231231",
                "prostatus": "1",
                "wordpath": null,
                "tasks": [
                    {
                        "id": 8,
                        "pid": "6",
                        "period": "0",
                        "target": "功能融合",
                        "dec": "将三原县原PVA，PVD和视频结构化平台单独运行，客户表示将结构化平台单独登录太繁琐，且平台数据没有拉通，需要PVA/PVD和结构化整合。",
                        "subProject": "三原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1,2",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "4",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547026410518"
                    },
                    {
                        "id": 14,
                        "pid": "6",
                        "period": "0",
                        "target": "更新",
                        "dec": "更新1",
                        "subProject": "三原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1,2,4",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "4",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547084097335"
                    },
                    {
                        "id": 20,
                        "pid": "6",
                        "period": "0",
                        "target": "更新2",
                        "dec": "更新",
                        "subProject": "四原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "6",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "4",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547030129566"
                    }
                ]
            },
            {
                "createdAt": "1547018321469",
                "updatedAt": "1547089668538",
                "id": 8,
                "name": "山西-太原-万柏林-修改",
                "area": "1",
                "dutyPerson": "3",
                "createPerson": "3",
                "prods": "1,2,3",
                "summary": "",
                "number": "00001",
                "prostatus": "2",
                "wordpath": "",
                "tasks": [
                    {
                        "id": 9,
                        "pid": "8",
                        "period": "0",
                        "target": "功能融合",
                        "dec": "将三原县原PVA，PVD和视频结构化平台单独运行，客户表示将结构化平台单独登录太繁琐，且平台数据没有拉通，需要PVA/PVD和结构化整合。",
                        "subProject": "三原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1,2",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "3",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547026430724"
                    },
                    {
                        "id": 15,
                        "pid": "8",
                        "period": "1",
                        "target": "功能融合",
                        "dec": "将三原县原PVA，PVD和视频结构化平台单独运行，客户表示将结构化平台单独登录太繁琐，且平台数据没有拉通，需要PVA/PVD和结构化整合。",
                        "subProject": "三原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1,2",
                        "version": "",
                        "proDutyPerson": "3",
                        "taskDutyPerson": "3",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547027162766"
                    }
                ]
            },
            {
                "createdAt": "1547108430177",
                "updatedAt": "1547108430177",
                "id": 9,
                "name": "陕西咸阳",
                "area": "1",
                "dutyPerson": "5",
                "createPerson": "3",
                "prods": "1",
                "summary": "",
                "number": "00001",
                "prostatus": "2",
                "wordpath": "",
                "tasks": [
                    {
                        "id": 16,
                        "pid": "9",
                        "period": "0",
                        "target": "功能融合",
                        "dec": "将三原县原PVA，PVD和视频结构化平台单独运行，客户表示将结构化平台单独登录太繁琐，且平台数据没有拉通，需要PVA/PVD和结构化整合。",
                        "subProject": "三原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "4",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547027129912"
                    },
                    {
                        "id": 10,
                        "pid": "9",
                        "period": "1",
                        "target": "更新2",
                        "dec": "更新",
                        "subProject": "四原",
                        "taskType": "1",
                        "sonType": "",
                        "deliveryType": "",
                        "prods": "1,2",
                        "version": "",
                        "proDutyPerson": "4",
                        "taskDutyPerson": "4",
                        "workload": "5",
                        "startDate": "1546932043246",
                        "endDate": "1546932043246",
                        "progress": "0",
                        "taskStatus": "0",
                        "status": "0",
                        "remark": "",
                        "createdAt": "1546617599999",
                        "updatedAt": "1547084097440"
                    }
                ]
            }
        ]
    }
]